language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.26"

env:
  AUTHOR_TESTING: 1
before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend .
  - cover -delete
script:
  - perl Build.PL
  - ./Build build
  - cover -test -report codecov
